## List

Exercise 1: Reverse a list in Python

In [ ]:
list1 = [10, 20, 30, 40, 50]

Exercise 2: Concatenate two lists index-wise
Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

In [ ]:
list1 = ["M", "na", "i", "Ke"]
list2 = ["y", "me", "s", "lly"]

Exercise 3: Turn every item of a list into its square
Given a list of numbers. write a program to turn every item of a list into its square.

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7]

Exercise 4: Concatenate two lists in the following order

In [ ]:
list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]

Exercise 5: Iterate both lists simultaneously
Given a two Python list. Write a program to iterate both lists simultaneously and display items from list1 in original order and items from list2 in reverse order.

In [ ]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

Exercise 6: Remove empty strings from the list of strings

In [ ]:
list1 = ["Mike", "", "Emma", "Kelly", "", "Brad"]

Exercise 7: Add new item to list after a specified item
Write a program to add item 7000 after 6000 in the following Python List

In [ ]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

## Dictionary

Exercise 1: Convert two lists into a dictionary
Below are the two lists. Write a Python program to convert them into a dictionary in a way that item from list1 is the key and item from list2 is the value

In [ ]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

Exercise 2: Merge two Python dictionaries into one

In [1]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

Exercise 3: Print the value of key ‘history’ from the below dict

In [2]:
sampleDict = {
    "class": {
        "student": {
            "name": "Mike",
            "marks": {
                "physics": 70,
                "history": 80
            }
        }
    }
}

Exercise 4: Initialize dictionary with default values
In Python, we can initialize the keys with the same values.

In [3]:
employees = ['Kelly', 'Emma']
defaults = {"designation": 'Developer', "salary": 8000}

Exercise 5: Create a dictionary by extracting the keys from a given dictionary

In [4]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"}

# Keys to extract
keys = ["name", "salary"]

Exercise 6: Delete a list of keys from a dictionary

In [5]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}

# Keys to remove
keys = ["name", "salary"]

Exercise 7: Check if a value exists in a dictionary
We know how to check if the key exists in a dictionary. Sometimes it is required to check if the given value is present.

Write a Python program to check if value 200 exists in the following dictionary.

In [6]:
sample_dict = {'a': 100, 'b': 200, 'c': 300}

Exercise 8: Rename key of a dictionary
Write a program to rename a key city to a location in the following dictionary.

In [7]:
sample_dict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

## Tuple

Exercise 1: Access value 20 from the tuple
The given tuple is a nested tuple. write a Python program to print the value 20.

In [8]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))

Exercise 2: Swap two tuples in Python

In [9]:
tuple1 = (11, 22)
tuple2 = (99, 88)

Exercise 3: Copy specific elements from one tuple to a new tuple
Write a program to copy elements 44 and 55 from the following tuple into a new tuple.

In [10]:
tuple1 = (11, 22, 33, 44, 55, 66)

Exercise 4: Modify the tuple
Given is a nested tuple. Write a program to modify the first item (22) of a list inside a following tuple to 222

`Expected output -> tuple1: (11, [222, 33], 44, 55)`

In [11]:
tuple1 = (11, [22, 33], 44, 55)

Exercise 5: Sort a tuple of tuples by 2nd item

In [12]:
tuple1 = (('a', 23),('b', 37),('c', 11), ('d',29))

Exercise 6: Counts the number of occurrences of item 50 from a tuple

In [13]:
tuple1 = (50, 10, 60, 70, 50)

Exercise 7: Check if all items in the tuple are the same

In [14]:
tuple1 = (45, 45, 45, 45)

## Set

Exercise 1: Add a list of elements to a set
Given a Python list, Write a program to add all its elements into a given set.

In [15]:
sample_set = {"Yellow", "Orange", "Black"}
sample_list = ["Blue", "Green", "Red"]

Exercise 2: Return a new set of identical items from two sets

In [16]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

Exercise 3: Update the first set with items that don’t exist in the second set
Given two Python sets, write a Python program to update the first set with items that exist only in the first set and not in the second set.

In [17]:
set1 = {10, 20, 30}
set2 = {20, 40, 50}

Exercise 4: Return a set of elements present in Set A or B, but not both

In [18]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

Exercise 5: Update set1 by adding items from set2, except common items

In [19]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

Exercise 6: Remove items from set1 that are not common to both set1 and set2

In [20]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}